### ISSUE TITLE
Not working on nuxt

### ISSUE THREAD

**Issue by nonybrighto** [Akryum/vue-mention#10]
Great plugin! I am having issues making it work on nuxt. I have tried implementing it as a plugin too but it doesn't work. I have also installed v-tooltip. Nothing shows up when I type in the @ symbol.

**plugins/vue-mention.js**

```
 import Vue from 'vue'
 import { Mentionable } from 'vue-mention'
 
 Vue.component('Mentionable', Mentionable)
```
**nuxt.config.js**

```
plugins: [
    { src: '~plugins/vue-mention', ssr: false }
  ]
```
**component.vue**
```
<template>
  <div>
    <Mentionable :keys="['@']" :items="items" offset="6">
      <textarea v-model="text" />
    </Mentionable>
  </div>
</template>
<script>
import { Mentionable } from 'vue-mention'
export default {
  components: {
    Mentionable
  },
  data() {
    return {
      text: '',
      items: [
        {
          value: 'cat',
          label: 'Mr Cat'
        },
        {
          value: 'dog',
          label: 'Mr Dog'
        }
      ]
    }
  }
}
</script>
```

**Comment by Akryum** [comment]
Did you setup v-tooltip?

Le sam. 20 juin 2020 à 07:09, Nony Bright O <notifications@github.com> a
écrit :

**Comment by nonybrighto** [comment]
@Akryum I installed v-tooltip. It gave a warning to install v-tooltip and the warning cleared after I did but nothing changed.

**Comment by jesuskinto** [comment]
I was able to get it working properly by following the steps in the Nuxt plugin guide 🥳.

`npm install --save v-tooltip`

We create the file `plugins/vue-tooltips.js`:
```
import Vue from 'vue'
import VTooltip from 'v-tooltip'

Vue.use(VTooltip)
```

Then we add the file path inside the plugins key of our nuxt.config.js:
```
export default {
  plugins: ['@/plugins/vue-tooltip.js']
}
```

**Comment by amdp** [comment]
Hi, I am on nuxt and I can actually mention (https://pasteboard.co/Jms7UjS.png) but I cannot see the tooltip, even if its state is open, even if I change the background-color and the z-index.

**Comment by quanghm27** [comment]
> Hi, I am on nuxt and I can actually mention (https://pasteboard.co/Jms7UjS.png) but I cannot see the tooltip, even if its state is open, even if I change the background-color and the z-index.

Did you install v-tooltip ?

**Comment by amdp** [comment]
yes of course!

**Comment by Rohan-Jalil** [comment]
@Akryum I'm trying to integrate it in a nuxt project. My nuxt version is 2.14.6. I'm also using bootstrap vue but the popover doesn't show up, I've tried applying styles too but it doesn't seem to work.
