### ISSUE TITLE
Its possible to fetch from api and populate directly?

### ISSUE THREAD

**Issue by osmelg** [Akryum/vue-mention#13]
As I have been reading in getting started, there is the possibility of obtaining data from an api and add it directly? axios ?. Or only can add data to the 'users' list from another method?
this.users = response.data

**Comment by Akryum** [comment]
You can do anything you want with it, it's just component data.

**Comment by osmelg** [comment]
Hello, my bad, i was using a browser extension for dark mode and I couldn't notice the other options available.

**Comment by osmelg** [comment]
I tried to make it work with axios, nothing happen. Did you have any working example using axios? @Akryum

**Comment by quanghm27** [comment]
@osmelg I think this demo link will help you
https://vue-mention.netlify.app/guide/async-items.html#final-demo
