### ISSUE TITLE
Any reason why this doesn't work?

### ISSUE THREAD

**Issue by cfmnephrite** [Akryum/vue-mention#19]
Simply nothing happens when I type @. This is inside a vue component with Vuetify and other libraries present.

```
<Mentionable
    :keys="['@']"
    :items="items"
>
    <textarea
        v-model="currentlyEditingCol.formula"
    />
</Mentionable>
...
items: [
    {
        value: 'example',
        label: 'Example'
    },
    {
        value: 'stuff',
        label: 'Stuff'
    },
    {
        value: 'list',
        label: 'List'
    }
],

**Comment by quanghm27** [comment]
@cfmnephrite you have to add v-tooltip also

`npm install v-tooltip`

Then import
```
import Vue from 'vue'
import VTooltip from 'v-tooltip'

Vue.use(VTooltip)

```
after that, you can the mention list will show

**Comment by cfmnephrite** [comment]
> @cfmnephrite you have to add v-tooltip also
> 
> `npm install v-tooltip`
> 
> Then import
> 
> ```
> import Vue from 'vue'
> import VTooltip from 'v-tooltip'
> 
> Vue.use(VTooltip)
> ```
> 
> after that, you can the mention list will show

V-Tooltip is installed as it has to be for vue-mention to run in the first place. The vue-mention files themselves also import directly from V-Tooltip. Nevertheless, I tried also loading both v-tooltip and v-popover, but had the exact same result.

**Comment by cfmnephrite** [comment]
Never mind, the source of the issue appears to be Bootstrap's CSS rendering the tooltip invisible, for some reason.

**Comment by kamenivskyi** [comment]
@cfmnephrite Hello have you fixed this issue? If so, can you please write your solution?
