### ISSUE TITLE
Vue3 support

### ISSUE THREAD

**Issue by czarkom** [Akryum/vue-mention#35]
Hello, could You please update vue-mention so as to make it available in Vue3? That would help a lot:)

**Comment by Sweetlegs** [comment]
Hi, could you please update vue-mention to work on Vue3 that would be great help thanks

**Comment by reslear** [comment]
any news?

**Comment by kayahasa** [comment]
any?

**Comment by Akryum** [comment]
Closed in 2.0.0-alpha.1
