### ISSUE TITLE
Placement of the Popper within ViewPort

### ISSUE THREAD

**Issue by HRankit** [Akryum/vue-mention#5]
First of all, thank you. Was searching for a good library for a long time.

I've created a basic sandbox and I'm unable to get the popper-list within the viewport. 
The Popper is always out of viewport and I'm unable to find relevant document on positioning of the popper.
I tried all possible `placement` properties of Vpopper. 

It would be great if a real working codepen or codesandbox will be made available along with relevant documentation.

Please have a look at the sandbox and let me know how to correct it.

https://codesandbox.io/s/vue-mention-sandbox-z5g17?file=/src/App.vue

Also, it'd be great if you could give an example with Vuetify v-textarea.

**Comment by Akryum** [comment]
https://codesandbox.io/s/vue-mention-sandbox-4wczg
