### ISSUE TITLE
Allow catch close menu event.

### ISSUE THREAD

**Issue by Rubon72** [Akryum/vue-mention#8]
Make @close="onCloseMentionMenu" like @open="onOpenMentionMenu"

**Comment by Rubon72** [comment]
`    closeMenu () {
      this.oldKey = this.key
      this.key = null
      **this.$emit('close')**  
    },`

add row this.$emit('close') to  closeMenu method

**Comment by Rubon72** [comment]
@Akryum

**Comment by quanghm27** [comment]
@Rubon72: Why you need this event, can you share your case ?

**Comment by Milos777** [comment]
Example for it could be that you want to type message and on key press ENTER you want to send it and if you type @ and typing some user name and press enter, it will send the message as well. With onClose you could at least make conditions. @quanghm27 @amdp
